export {default as Game } from './molecules/Game'
export {default as StartModal } from './molecules/StartModal'
export {default as JavascriptLogo } from './atoms/JavascriptLogo'
export {default as Footer } from './atoms/Footer'
export {default as StatisticsModal } from './molecules/StatisticsModal'
